# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
     # the username
    user: root
      # the password
    password:
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/phonebook
    properties:
      charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.hbm2ddl.auto: update

template: Hello, %s!
defaultName: back-end
server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8001
